### ISSUE TITLE
Error in traefik config file

### ISSUE THREAD

**Issue by archnode** [rolehippie/traefik#31]
First of all, thanks for the great up-to-date docker and traefik roles!

I've tried them out and stumbled upon an issue with traefik not working:

`command traefik error: field not found, node: ansible.builtin.file`

As I'm not very familiar with ansible and templating - can the jinja templates use ansible functionality as seen here? The ansible parts don't seem to get replaced in my case.

https://github.com/rolehippie/traefik/blob/bdd7ff50af2903b300bfd7babf7d1b01c8a60fe5/templates/config.j2#L61

**Comment by tboerger** [comment]
Thanks for the catch, that's just a search and replace accident while switching to fully qualified resource names. Currently I'm on a conference, so it's difficult to fix from my side.

**Comment by archnode** [comment]
No worries, I created a pr that straight up removes the commands, just as a placeholder. https://github.com/rolehippie/traefik/pull/32

**Comment by tboerger** [comment]
The new release would work correctly :)
